Добавляет базовую стилизацию всех страниц
htmlacademy-htmlcss/791627-sedona-34 pull request #4
Opened 2022-06-04 12:45 UTC by zhorman

2022-06-04 19:00 UTC, andreysgra requested changes

2022-06-04 19:00 UTC, andreysgra commented on .editorconfig
> +insert_final_newline = false
А вот этот файл править не нужно 😏 . Верните значение на `true`. Пустая новая строка в конце файла нужна в соответствии с требованиями оформления кода.

2022-06-04 19:00 UTC, andreysgra commented on catalog.html
> +      <section class="main-catalog-header">
Особого смысла в использовании тега `section` здесь я не вижу. Родительским элементом является `section` с классом `main-catalog`. Здесь лучше использовать простой `div`, если нужна обёртка для внутренних блоков.

2022-06-04 19:00 UTC, andreysgra commented on index.html
> +        <img class="page-header-logo" alt="Логотип город Седона." src="/images/vector-icons/logo-sedona.svg">
В самом начале относительного пути слеша не должно быть, иначе браузер не найдёт файл, что мы и наблюдаем:
![image](https://user-images.githubusercontent.com/17790771/172021666-ff5be526-5ccc-462a-87e9-04a134cdef12.png)

2022-06-04 19:00 UTC, andreysgra commented on index.html
> +    <img class="main-logo" src="/images/vector-icons/sedona-welcome-logo.svg" alt="Логотип города Седона.">
Аналогичная проблема:
![image](https://user-images.githubusercontent.com/17790771/172021678-0894ac2f-c985-4496-8845-8f4e16b54e28.png)

2022-06-04 19:00 UTC, andreysgra commented on styles/styles.css
> +  background-color: rgb(136, 199, 201);
Если цвет не содержит альфа-канала (прозрачность), то значение нужно указывать в HEX-формате. Есть такой критерий [PROJ-01](https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01). Конкретнее можно посмотреть [здесь](http://codeguide.academy/html-css.html#css-color-format).

2022-06-04 19:00 UTC, andreysgra commented on styles/styles.css
> +  background-color: rgb(83, 151, 168);
Аналогичное замечание.

2022-06-04 19:00 UTC, andreysgra commented on styles/styles.css
> +  text-transform: capitalize;
А вы уверены, что вам нужно чтобы каждое слово начиналось с заглавной буквы?

2022-06-04 19:00 UTC, andreysgra commented on styles/styles.css
> +  color: #00000;
Не хватает одного `0`.

2022-06-04 19:00 UTC, andreysgra commented on styles/styles.css
> +  color: #000000;
Это к самому первому замечанию, что не нужно править файл .editorconfig.

2022-06-04 21:41 UTC, zhorman commented on styles/styles.css
> +  text-transform: capitalize;
просто в макете был такой `text-transform:` у текста и `Тип Жилья` с большой буквы оба слова
а  как лучше, в `<legend class="catalog-filter-title">Тип Жилья:</legend>` прописать с большой буквы? 
или в CSS оставить `text-transform: capitalize;` только для этого текста

2022-06-05 15:37 UTC, andreysgra commented on styles/styles.css
> +  text-transform: capitalize;
Раз в макете так написано, то вы поступили правильно. Я проверял задание не заглядывая в макет и мне показалось странным, что каждое слово фразы начинается с заглавной буквы.

2022-06-05 15:39 UTC, merged